Repository ploigos/ploigos-step-runner, pull requests merged in 2020-09, with the labels that each got.

#67 Documentation Updates (corrections and additions) for static-code-analysis and push-artifacts
  README.md
  tssc/__init__.py
  tssc/step_implementers/package/__init__.py
  tssc/step_implementers/push_artifacts/__init__.py
  tssc/step_implementers/push_artifacts/maven.py
  tssc/step_implementers/static_code_analysis/__init__.py
  tssc/step_implementers/static_code_analysis/sonarqube.py
Labels: documentation, enhancement

#71 NAPSSPO-954 - added endpoint url to results
  tests/step_implementers/deploy/test_argocd.py
  tssc/step_implementers/deploy/argocd.py
Labels: bug

#70 NAPSSPO-955 - tssc-python-library - refactor step_implementer to not pass configuration as a dict and refactor all step implementers to get configuration from TSSC*Config objects
  tests/helpers/sample_step_implementers.py
  tests/helpers/test_utils.py
  tests/step_implementers/deploy/test_argocd.py
  tests/test_config.py
  tests/test_step_implementer.py
  tssc/config.py
  tssc/step_implementer.py
  tssc/step_implementers/canary_test/selenium.py
  tssc/step_implementers/container_image_static_compliance_scan/openscap.py
  tssc/step_implementers/container_image_static_vulnerability_scan/openscap.py
  tssc/step_implementers/create_container_image/buildah.py
  tssc/step_implementers/deploy/argocd.py
  tssc/step_implementers/generate_metadata/git.py
  tssc/step_implementers/generate_metadata/maven.py
  tssc/step_implementers/generate_metadata/npm.py
  tssc/step_implementers/generate_metadata/semantic_version.py
  tssc/step_implementers/package/maven.py
  tssc/step_implementers/package/npm.py
  tssc/step_implementers/push_artifacts/maven.py
  tssc/step_implementers/push_artifacts/npm.py
  tssc/step_implementers/push_container_image/skopeo.py
  tssc/step_implementers/static_code_analysis/sonarqube.py
  tssc/step_implementers/tag_source/git.py
  tssc/step_implementers/uat/cucumber.py
  tssc/step_implementers/unit_test/maven.py
Labels: enhancement

#74 refactor config.py into seperate modules for maintainability
  tests/config/test_config.py
  tests/config/test_step_config.py
  tests/config/test_sub_step_config.py
  tests/test_factory.py
  tests/test_main.py
  tests/test_step_implementer.py
  tssc/__init__.py
  tssc/__main__.py
  tssc/config.py
  tssc/config/__init__.py
  tssc/config/config.py
  tssc/config/step_config.py
  tssc/config/sub_step_config.py
Labels: enhancement

#77 NAPSSPO-597 - introduce TSSCConfigValue
  tests/config/test_config.py
  tests/config/test_config_value.py
  tests/config/test_step_config.py
  tests/config/test_sub_step_config.py
  tests/helpers/sample_step_implementers.py
  tssc/config/__init__.py
  tssc/config/config.py
  tssc/config/config_value.py
  tssc/config/sub_step_config.py
  tssc/step_implementer.py
  tssc/step_implementers/deploy/argocd.py
  tssc/step_implementers/static_code_analysis/sonarqube.py
Labels: enhancement

#73 Feature/napsspo 346 : container_image_static_compliance_scan
  tests/step_implementers/container_image_static_compliance_scan/test_openscap_compliance.py
  tssc/__init__.py
  tssc/step_implementers/container_image_static_compliance_scan/openscap.py
  tssc/step_implementers/deploy/argocd.py
Labels: enhancement

#81 NAPSSPO-1013 - add utility function for logging into authenticated container registry
  tests/helpers/test_utils.py
  tests/step_implementers/create_container_image/test_buildah.py
  tests/step_implementers/deploy/test_argocd.py
  tests/step_implementers/push_container_image/test_skopeo.py
  tests/test_step_implementer.py
  tests/utils/test_containers.py
  tssc/__init__.py
  tssc/step_implementer.py
  tssc/step_implementers/create_container_image/buildah.py
  tssc/step_implementers/push_container_image/skopeo.py
  tssc/utils/__init__.py
  tssc/utils/containers.py
Labels: enhancement

#80 Feature/napsspo 996 : use a settings.xml for all maven steps to allow for disconnected.
  tests/step_implementers/package/test_maven_package.py
  tests/step_implementers/push_artifacts/test_maven_push_artifacts.py
  tests/step_implementers/uat/uat_maven_test.py
  tests/step_implementers/unit_test/test_maven_unit_test.py
  tests/utils/test_maven.py
  tssc/__init__.py
  tssc/step_implementers/package/maven.py
  tssc/step_implementers/push_artifacts/__init__.py
  tssc/step_implementers/push_artifacts/maven.py
  tssc/step_implementers/uat/maven.py
  tssc/step_implementers/unit_test/maven.py
  tssc/utils/__init__.py
  tssc/utils/maven.py
  tssc/utils/xml.py
Labels: enhancement

#84 NAPSSPO-1029 - tssc-python-library - tag-source (Git) - if url not provided and CI tool checks out source using username and tssc config provides a username/pass then everything breaks
  tests/step_implementers/tag_source/test_git.py
  tssc/step_implementer.py
  tssc/step_implementers/tag_source/git.py
Labels: bug
