Repository ploigos/ploigos-step-runner, pull requests merged in 2021-07, with the labels that each got.

#164 sign image from authed registry
  README.md
  src/ploigos_step_runner/step_implementers/push_container_image/skopeo.py
  src/ploigos_step_runner/step_implementers/sign_container_image/podman_sign.py
  src/ploigos_step_runner/utils/containers.py
  tests/step_implementers/push_container_image/test_skopeo_push_container_image.py
  tests/step_implementers/sign_container_image/test_podman_sign.py
  tests/utils/test_containers.py
Labels: enhancement

#167 Feature/opa
  src/ploigos_step_runner/__init__.py
Labels: documentation

#174 Fixes issue where config.yml values were returned as ConfigValue objects when calling get_value()
  src/ploigos_step_runner/config/sub_step_config.py
  tests/config/test_sub_step_config.py
Labels: bug

#175 BREAKING (possibly): removes defaulting storage driver to vfs for podman/buildah/skopeo operations
  src/ploigos_step_runner/step_implementers/create_container_image/buildah.py
  tests/step_implementers/create_container_image/test_buildah_create_container_image.py
Labels: enhancement
